import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import * as React from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const menuStyles: React.CSSProperties = {
  display: 'flex',
  justifyContent: 'flex-end',
  padding: '1rem',
  borderBottom: '1px solid #ccc',
  borderLeft: '1px solid #ccc',
  position: 'absolute',
  right: 0
}

const menuLinkStyles: React.CSSProperties = {
  padding: '0 1rem',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          style={menuStyles}
        >
          <a style={menuLinkStyles} href="/">Create a New Space</a>
          <a style={menuLinkStyles} href="/re-used-space">Re-use a Space</a>
          <a style={menuLinkStyles} href="/sheet">Sheet</a>
          <a style={menuLinkStyles} href="/workbook">Workbook</a>
        </div>
        {children}
      </body>
    </html>
  )
}
