export * from './IReactInitSpaceProps'
export * from './IReactSpaceProps'
export * from './iFrameProps'
export * from './IFlatfileProvider'
export * from './ICreateSpaceInternal'
export * from './IClosePortal'